Parse summary
biowdl/clinical-validation pull request #4
Opened 2020-10-01 07:18 UTC by Redmar-van-den-Berg

Parse the separate summary output files for SNPs and indels for each sample into two tables, and also add an html graph showing the indel and SNP precision and sensitivity for each sample for easy comparison.

2020-10-05 08:08 UTC, DavyCats requested changes, later dismissed

2020-10-05 08:08 UTC, DavyCats commented on clinical-validation.wdl
> +        memory: {description: "The amount of memory to use.", category: "required"}
```suggestion
        dockerImage: {description: "The docker images used.", category: "advanced"}
        memory: {description: "The amount of memory to use.", category: "advanced"}
```

2020-10-05 08:08 UTC, DavyCats commented on clinical-validation.wdl
> +    parameter_meta {
Most inputs are missing here

2021-07-06 10:00 UTC, rhpvorderman approved these changes

2021-07-06 10:00 UTC, rhpvorderman commented on src/parse_summary.py
> +def print_tsv(data, filename):
This function is a bit complicated due to the writefile partial. why not:
```python
    with open(filename, 'wt') as fout:
        fout.write("Sample\t" + "\t".join(expected_header) + "\n")
        for sample in data:
            for entry in data[sample]:
                fout.write(sample + "\t" + "\t".join(entry[field] for field in expected_header) + "\n")
```

2021-07-06 10:01 UTC, rhpvorderman commented on src/parse_summary.py
> +def print_tsv(data, filename):
Whoops. Forgot the `"\n"` s. But anyway. No need to write a partial function when Python File objects have write methods.

2021-07-06 11:48 UTC, merged